name: pytesting

on: push

jobs:
  pytest:
    name: Test code with pytest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: action/setup-python@v2
        with:
          python-version: 3.8.2
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest